### ISSUE TITLE
make `libunwind` as a optional dependency

### ISSUE THREAD

**Issue by wxymh** [libsese/sese#63]
I'm trying to port this library to a platform that uses musl.

But I found that `StackInfo` uses e.g. `backtrace` which is not implemented in musl, is it possible to introduce e.g. `libunwind` to solve this problem?

I tried using some port of libexecinfo, but the program still crashes.

By the way, even though I see yours efforts at internationalization, unfortunately there are still too many notes that I didn't fully understand...😿

**Comment by SHIINASAMA** [comment]
We have no plans to support other libraries or platforms. glibc is sufficient for now. If you wish to implement this you can fork a branch yourself to do so. Of course I'm happy to accept contributions to the upstream if you're willing to do so, the minimum requirement is that you don't break existing compatibility.
