### ISSUE TITLE
[general]: Amiguous git identifers

### ISSUE THREAD

**Issue by dg0yt** [libsese/sese#85]
At the moment, `2.3.0` exists both as a git tag and as a git branch. The ambiguous identifier leads to unexpected interactions, e.g. on github. This was noticed in vcpkg, https://github.com/microsoft/vcpkg/pull/42420.

Suggestions:
 - Rename the `2.3.0` branch, e.g. to `2.3` or `2.3.x`.
 - Use release tags with `v` prefix, i.e. `v2.3.0`.

**Comment by SHIINASAMA** [comment]
Branch `2.3.0` has been renamed to `release-2.3.0`.

The project builds correctly locally with the latest vcpkg version. Does this still require any changes to the vcpkg port?
